services:
  db:
    image: postgres:15-alpine
    container_name: monica_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rio_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: monica_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: monica_secret_123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: monica_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always