import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

/**
 * Metadatos de la aplicación.
 * Configuración global de SEO y título.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Layout Principal (RootLayout)
 * 
 * Estructura base para todas las páginas de la aplicación.
 * Incluye la configuración de fuentes (Geist), el Navbar global y el contenedor principal.
 * 
 * @param {Object} props - Propiedades del componente.
 * @param {React.ReactNode} props.children - Contenido hijo a renderizar.
 * @returns {JSX.Element} Estructura HTML base.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar />
        <main className="pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
